name: exception_widget
description: Flutter package that allows to deal with different widgets mapped by exception
version: 0.0.1
repository: https://github.com/dariof28/exception_widget

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
